version: '2.2'
services:

  mongo_backup:
    image: nikashitsa/mongo-backup
    mem_limit: 50mb # perhaps you need to increase this limit
    cpus: 0.5 # 50%
    volumes:
      - /mongo-backup/cache:/root/.cache/duplicity
    environment:
      REMOTE_URL: 's3://s3.eu-central-1.amazonaws.com/mongo-backup/backups'
      PARAMS: 'full --volsize=200 --s3-multipart-chunk-size=100'
      MONGO_DUMP_PARAMS: '-d mydatabase --gzip'
      MONGO_RESTORE_PARAMS: '--drop --gzip'
      BACKUP_LIFETIME: '30D' # remove old (30 days) backups. Remove this line to keep all backups
      BACKUP_TIME: '0 3 * * *' # once per day.
      AWS_ACCESS_KEY_ID: 'put your value here'
      AWS_SECRET_ACCESS_KEY: 'put your value here'
      TELEGRAM_TOKEN: 'put your value here' # optional
      TELEGRAM_CHAT_ID: 'put your value here' # optional
    links:
      - db:mongo
    logging:
      options:
        max-size: '10m'
        max-file: '5'

  db:
    image: mongo:3.2
