version: '2.2'
services:

  mongo_backup:
    build: .
    mem_limit: 50mb
    cpus: 0.5
    environment:
      REMOTE_URL: ''
      PARAMS: ''
      MONGO_DUMP_PARAMS: ''
      MONGO_RESTORE_PARAMS: ''
      BACKUP_LIFETIME: ''
      BACKUP_TIME: ''
      AWS_ACCESS_KEY_ID: ''
      AWS_SECRET_ACCESS_KEY: ''
      TELEGRAM_TOKEN: ''
      TELEGRAM_CHAT_ID: ''
    volumes:
      - ./cache:/root/.cache/duplicity
    links:
      - db:mongo

  db:
    image: mongo:3.2
